                                                                                                    import java.util.*;                                                                                                    
                                                                                                    import soot.*;                                                                                                    
                                                                                                    import soot.jimple.*;                                                                                                    
                                                                                                    import soot.util.*;                                                                                                    
                                                                                                                                                                                                        
                                                                                                    public class                                                                                                     org_apache_tomcat_dbcp_dbcp_datasources_SequencedHashMap$1_Maker                                                                                                     {                                                                                                    
                                                                                                    private static Local localByName(Body b, String name) {                                                                                                    
                                                                                                    	for(Local l: b.getLocals()) {                                                                                                    
                                                                                                    		if(l.getName().equals(name))                                                                                                    
                                                                                                    			return l;                                                                                                    
                                                                                                    	}                                                                                                    
                                                                                                    	throw new IllegalArgumentException("No such local: "+name);                                                                                                    
                                                                                                    }                                                                                                    
                                                                                                      public void create() {                                                                                                      
                                                                                                        SootClass c = new SootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1");                                                                                                        
                                                                                                        c.setApplicationClass();                                                                                                        
                                                                                                        Scene.v().addClass(c);                                                                                                        
                                                                                                        createMethod0(c);                                                                                                        
                                                                                                        createMethod1(c);                                                                                                        
                                                                                                        createMethod2(c);                                                                                                        
                                                                                                        createMethod3(c);                                                                                                        
                                                                                                        createMethod4(c);                                                                                                        
                                                                                                        createMethod5(c);                                                                                                        
                                                                                                        createMethod6(c);                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod0(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1"),"this$0",type,false);                                                                                                          Value lhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs0 = localByName(b,"r1");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.util.AbstractSet"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod1(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("iterator",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$OrderedIterator")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        RefType type1 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$OrderedIterator");                                                                                                        
                                                                                                        Value rhs0 = Jimple.v().newNewExpr(type1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1"),"this$0",type,false);                                                                                                          Value rhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type type1 = IntType.v();                                                                                                          
                                                                                                          parameterTypes.add(type1);                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$OrderedIterator"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$r1");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod2(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("remove",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r2", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$Entry")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r3", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        NopStmt jumpTarget1= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r3");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1"),"this$0",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"r2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          RefType type1 = RefType.v("java.lang.Object");                                                                                                          
                                                                                                          parameterTypes.add(type1);                                                                                                          
                                                                                                          RefType returnType = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$Entry");                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap"),"access$000",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value rhs1 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs1));                                                                                                        
                                                                                                        Local left0 = localByName(b,"r2");                                                                                                        
                                                                                                        Value right0 = NullConstant.v();                                                                                                        
                                                                                                        Value condition0 = Jimple.v().newEqExpr(left0,right0);                                                                                                        
                                                                                                        Unit target0=jumpTarget0;                                                                                                        
                                                                                                        units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                                        
                                                                                                        Local lhs4 = localByName(b,"$z0");                                                                                                        
                                                                                                        Value rhs2 = IntConstant.v(1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs2));                                                                                                        
                                                                                                        Unit target1=jumpTarget1;                                                                                                        
                                                                                                        units.add(Jimple.v().newGotoStmt(target1));                                                                                                        
                                                                                                        Local lhs5 = localByName(b,"$z0");                                                                                                        
                                                                                                        Value rhs3 = IntConstant.v(0);                                                                                                        
                                                                                                        units.add(jumpTarget0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs5,rhs3));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$z0");                                                                                                        
                                                                                                        units.add(jumpTarget1);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod3(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("clear",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1"),"this$0",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap"),"clear",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod4(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("size",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i0", RefType.v("int")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1"),"this$0",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$i0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = IntType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap"),"size",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$i0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod5(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("isEmpty",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1"),"this$0",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$z0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = BooleanType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap"),"isEmpty",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$z0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod6(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("contains",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap$1"),"this$0",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"$z0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r2");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("java.lang.Object");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = BooleanType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.datasources.SequencedHashMap"),"containsKey",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs1));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$z0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
