                                                                                                    import java.util.*;                                                                                                    
                                                                                                    import soot.*;                                                                                                    
                                                                                                    import soot.jimple.*;                                                                                                    
                                                                                                    import soot.util.*;                                                                                                    
                                                                                                                                                                                                        
                                                                                                    public class                                                                                                     org_apache_tomcat_dbcp_pool_impl_EvictionTimer_Maker                                                                                                     {                                                                                                    
                                                                                                    private static Local localByName(Body b, String name) {                                                                                                    
                                                                                                    	for(Local l: b.getLocals()) {                                                                                                    
                                                                                                    		if(l.getName().equals(name))                                                                                                    
                                                                                                    			return l;                                                                                                    
                                                                                                    	}                                                                                                    
                                                                                                    	throw new IllegalArgumentException("No such local: "+name);                                                                                                    
                                                                                                    }                                                                                                    
                                                                                                      public void create() {                                                                                                      
                                                                                                        SootClass c = new SootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer");                                                                                                        
                                                                                                        c.setApplicationClass();                                                                                                        
                                                                                                        Scene.v().addClass(c);                                                                                                        
                                                                                                        createMethod0(c);                                                                                                        
                                                                                                        createMethod1(c);                                                                                                        
                                                                                                        createMethod2(c);                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod0(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.EvictionTimer")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.EvictionTimer");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Object"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod1(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("schedule",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("java.util.TimerTask")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("l0", RefType.v("long")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("l1", RefType.v("long")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("java.util.Timer")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("java.util.Timer")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i2", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i3", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r3", RefType.v("java.util.Timer")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.util.TimerTask");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"l0");                                                                                                        
                                                                                                        Type paramType1 = LongType.v();                                                                                                        
                                                                                                        int number1=1;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType1, number1);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"l1");                                                                                                        
                                                                                                        Type paramType2 = LongType.v();                                                                                                        
                                                                                                        int number2=2;                                                                                                        
                                                                                                        Value idRef2 = Jimple.v().newParameterRef(paramType2, number2);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs2,idRef2));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"$r1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("java.util.Timer");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_timer",type,true);                                                                                                          Value rhs0 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs0));                                                                                                        
                                                                                                        Value left0 = NullConstant.v();                                                                                                        
                                                                                                        Local right0 = localByName(b,"$r1");                                                                                                        
                                                                                                        Value condition0 = Jimple.v().newNeExpr(left0,right0);                                                                                                        
                                                                                                        Unit target0=jumpTarget0;                                                                                                        
                                                                                                        units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                                        
                                                                                                        Local lhs4 = localByName(b,"$r2");                                                                                                        
                                                                                                        RefType type0 = RefType.v("java.util.Timer");                                                                                                        
                                                                                                        Value rhs1 = Jimple.v().newNewExpr(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r2");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type type0 = BooleanType.v();                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.util.Timer"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("java.util.Timer");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_timer",type,true);                                                                                                          Value lhs5 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs2 = localByName(b,"$r2");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs5,rhs2));                                                                                                        
                                                                                                        Local lhs6 = localByName(b,"$i2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_usageCount",type,true);                                                                                                          Value rhs3 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(jumpTarget0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs6,rhs3));                                                                                                        
                                                                                                        Local lhs7 = localByName(b,"$i3");                                                                                                        
                                                                                                        Local left1 = localByName(b,"$i2");                                                                                                        
                                                                                                        Value right1 = IntConstant.v(1);                                                                                                        
                                                                                                        Value rhs4 = Jimple.v().newAddExpr(left1,right1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs7,rhs4));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_usageCount",type,true);                                                                                                          Value lhs8 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs5 = localByName(b,"$i3");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs8,rhs5));                                                                                                        
                                                                                                        Local lhs9 = localByName(b,"$r3");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("java.util.Timer");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_timer",type,true);                                                                                                          Value rhs6 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs9,rhs6));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r3");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("java.util.TimerTask");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type type1 = LongType.v();                                                                                                          
                                                                                                          parameterTypes.add(type1);                                                                                                          
                                                                                                          Type type2 = LongType.v();                                                                                                          
                                                                                                          parameterTypes.add(type2);                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.util.Timer"),"schedule",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie1));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod2(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("cancel",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("java.util.TimerTask")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i0", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i1", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i2", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("java.util.Timer")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.util.TimerTask");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = BooleanType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.util.TimerTask"),"cancel",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$i0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_usageCount",type,true);                                                                                                          Value rhs0 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$i1");                                                                                                        
                                                                                                        Local left0 = localByName(b,"$i0");                                                                                                        
                                                                                                        Value right0 = IntConstant.v(1);                                                                                                        
                                                                                                        Value rhs1 = Jimple.v().newSubExpr(left0,right0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_usageCount",type,true);                                                                                                          Value lhs3 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs2 = localByName(b,"$i1");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs2));                                                                                                        
                                                                                                        Local lhs4 = localByName(b,"$i2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_usageCount",type,true);                                                                                                          Value rhs3 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs3));                                                                                                        
                                                                                                        Local left1 = localByName(b,"$i2");                                                                                                        
                                                                                                        Value right1 = IntConstant.v(0);                                                                                                        
                                                                                                        Value condition0 = Jimple.v().newNeExpr(left1,right1);                                                                                                        
                                                                                                        Unit target0=jumpTarget0;                                                                                                        
                                                                                                        units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                                        
                                                                                                        Local lhs5 = localByName(b,"$r1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("java.util.Timer");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_timer",type,true);                                                                                                          Value rhs4 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs5,rhs4));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.util.Timer"),"cancel",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("java.util.Timer");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.EvictionTimer"),"_timer",type,true);                                                                                                          Value lhs6 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs5 = NullConstant.v();                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs6,rhs5));                                                                                                        
                                                                                                        units.add(jumpTarget0);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
