                                                                                                    import java.util.*;                                                                                                    
                                                                                                    import soot.*;                                                                                                    
                                                                                                    import soot.jimple.*;                                                                                                    
                                                                                                    import soot.util.*;                                                                                                    
                                                                                                                                                                                                        
                                                                                                    public class                                                                                                     org_apache_tomcat_dbcp_pool_impl_GenericKeyedObjectPool$Evictor_Maker                                                                                                     {                                                                                                    
                                                                                                    private static Local localByName(Body b, String name) {                                                                                                    
                                                                                                    	for(Local l: b.getLocals()) {                                                                                                    
                                                                                                    		if(l.getName().equals(name))                                                                                                    
                                                                                                    			return l;                                                                                                    
                                                                                                    	}                                                                                                    
                                                                                                    	throw new IllegalArgumentException("No such local: "+name);                                                                                                    
                                                                                                    }                                                                                                    
                                                                                                      public void create() {                                                                                                      
                                                                                                        SootClass c = new SootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor");                                                                                                        
                                                                                                        c.setApplicationClass();                                                                                                        
                                                                                                        Scene.v().addClass(c);                                                                                                        
                                                                                                        createMethod0(c);                                                                                                        
                                                                                                        createMethod1(c);                                                                                                        
                                                                                                        createMethod2(c);                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod0(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor"),"this$0",type,false);                                                                                                          Value lhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs0 = localByName(b,"r1");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.util.TimerTask"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod1(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("run",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Exception")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r3", RefType.v("java.lang.Exception")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r4", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r5", RefType.v("java.lang.Exception")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r6", RefType.v("java.lang.Exception")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        NopStmt jumpTarget1= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor"),"this$0",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r2");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool"),"evict",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Unit target0=jumpTarget0;                                                                                                        
                                                                                                        units.add(Jimple.v().newGotoStmt(target0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r3");                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newCaughtExceptionRef();                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs2,idRef1));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"r1");                                                                                                        
                                                                                                        Local rhs1 = localByName(b,"$r3");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs1));                                                                                                        
                                                                                                        Local lhs4 = localByName(b,"$r4");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor"),"this$0",type,false);                                                                                                          Value rhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(jumpTarget0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs2));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool"),"access$500",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value ie1 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie1));                                                                                                        
                                                                                                        Unit target1=jumpTarget1;                                                                                                        
                                                                                                        units.add(Jimple.v().newGotoStmt(target1));                                                                                                        
                                                                                                        Local lhs5 = localByName(b,"$r5");                                                                                                        
                                                                                                        Value idRef2 = Jimple.v().newCaughtExceptionRef();                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs5,idRef2));                                                                                                        
                                                                                                        Local lhs6 = localByName(b,"r6");                                                                                                        
                                                                                                        Local rhs3 = localByName(b,"$r5");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs6,rhs3));                                                                                                        
                                                                                                        units.add(jumpTarget1);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod2(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r2", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$1")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"r2");                                                                                                        
                                                                                                        RefType paramType1 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$1");                                                                                                        
                                                                                                        int number1=1;                                                                                                        
                                                                                                        Value idRef2 = Jimple.v().newParameterRef(paramType1, number1);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs2,idRef2));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Evictor"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
