                                                                                                    import java.util.*;                                                                                                    
                                                                                                    import soot.*;                                                                                                    
                                                                                                    import soot.jimple.*;                                                                                                    
                                                                                                    import soot.util.*;                                                                                                    
                                                                                                                                                                                                        
                                                                                                    public class                                                                                                     org_apache_tomcat_dbcp_pool_impl_GenericKeyedObjectPool$Config_Maker                                                                                                     {                                                                                                    
                                                                                                    private static Local localByName(Body b, String name) {                                                                                                    
                                                                                                    	for(Local l: b.getLocals()) {                                                                                                    
                                                                                                    		if(l.getName().equals(name))                                                                                                    
                                                                                                    			return l;                                                                                                    
                                                                                                    	}                                                                                                    
                                                                                                    	throw new IllegalArgumentException("No such local: "+name);                                                                                                    
                                                                                                    }                                                                                                    
                                                                                                      public void create() {                                                                                                      
                                                                                                        SootClass c = new SootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config");                                                                                                        
                                                                                                        c.setApplicationClass();                                                                                                        
                                                                                                        Scene.v().addClass(c);                                                                                                        
                                                                                                        createMethod0(c);                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod0(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Object"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"maxIdle",type,false);                                                                                                          Value lhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs0 = IntConstant.v(8);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"maxActive",type,false);                                                                                                          Value lhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs1 = IntConstant.v(8);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"maxTotal",type,false);                                                                                                          Value lhs3 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs2 = IntConstant.v(-1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs2));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"minIdle",type,false);                                                                                                          Value lhs4 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs3 = IntConstant.v(0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs3));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = LongType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"maxWait",type,false);                                                                                                          Value lhs5 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs4 = LongConstant.v(-1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs5,rhs4));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = ByteType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"whenExhaustedAction",type,false);                                                                                                          Value lhs6 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs5 = IntConstant.v(1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs6,rhs5));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"testOnBorrow",type,false);                                                                                                          Value lhs7 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs6 = IntConstant.v(0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs7,rhs6));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"testOnReturn",type,false);                                                                                                          Value lhs8 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs7 = IntConstant.v(0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs8,rhs7));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"testWhileIdle",type,false);                                                                                                          Value lhs9 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs8 = IntConstant.v(0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs9,rhs8));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = LongType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"timeBetweenEvictionRunsMillis",type,false);                                                                                                          Value lhs10 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs9 = LongConstant.v(-1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs10,rhs9));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"numTestsPerEvictionRun",type,false);                                                                                                          Value lhs11 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs10 = IntConstant.v(3);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs11,rhs10));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = LongType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"minEvictableIdleTimeMillis",type,false);                                                                                                          Value lhs12 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs11 = LongConstant.v(1800000);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs12,rhs11));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$Config"),"lifo",type,false);                                                                                                          Value lhs13 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs12 = IntConstant.v(1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs13,rhs12));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
