                                                                                                    import java.util.*;                                                                                                    
                                                                                                    import soot.*;                                                                                                    
                                                                                                    import soot.jimple.*;                                                                                                    
                                                                                                    import soot.util.*;                                                                                                    
                                                                                                                                                                                                        
                                                                                                    public class                                                                                                     org_apache_tomcat_dbcp_pool_impl_GenericKeyedObjectPool$1_Maker                                                                                                     {                                                                                                    
                                                                                                    private static Local localByName(Body b, String name) {                                                                                                    
                                                                                                    	for(Local l: b.getLocals()) {                                                                                                    
                                                                                                    		if(l.getName().equals(name))                                                                                                    
                                                                                                    			return l;                                                                                                    
                                                                                                    	}                                                                                                    
                                                                                                    	throw new IllegalArgumentException("No such local: "+name);                                                                                                    
                                                                                                    }                                                                                                    
                                                                                                      public void create() {                                                                                                      
                                                                                                        SootClass c = new SootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$1");                                                                                                        
                                                                                                        c.setApplicationClass();                                                                                                        
                                                                                                        Scene.v().addClass(c);                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
