                                                                                                    import java.util.*;                                                                                                    
                                                                                                    import soot.*;                                                                                                    
                                                                                                    import soot.jimple.*;                                                                                                    
                                                                                                    import soot.util.*;                                                                                                    
                                                                                                                                                                                                        
                                                                                                    public class                                                                                                     org_apache_tomcat_dbcp_dbcp_AbandonedConfig_Maker                                                                                                     {                                                                                                    
                                                                                                    private static Local localByName(Body b, String name) {                                                                                                    
                                                                                                    	for(Local l: b.getLocals()) {                                                                                                    
                                                                                                    		if(l.getName().equals(name))                                                                                                    
                                                                                                    			return l;                                                                                                    
                                                                                                    	}                                                                                                    
                                                                                                    	throw new IllegalArgumentException("No such local: "+name);                                                                                                    
                                                                                                    }                                                                                                    
                                                                                                      public void create() {                                                                                                      
                                                                                                        SootClass c = new SootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig");                                                                                                        
                                                                                                        c.setApplicationClass();                                                                                                        
                                                                                                        Scene.v().addClass(c);                                                                                                        
                                                                                                        createMethod0(c);                                                                                                        
                                                                                                        createMethod1(c);                                                                                                        
                                                                                                        createMethod2(c);                                                                                                        
                                                                                                        createMethod3(c);                                                                                                        
                                                                                                        createMethod4(c);                                                                                                        
                                                                                                        createMethod5(c);                                                                                                        
                                                                                                        createMethod6(c);                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod0(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Object"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"removeAbandoned",type,false);                                                                                                          Value lhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs0 = IntConstant.v(0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"removeAbandonedTimeout",type,false);                                                                                                          Value lhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs1 = IntConstant.v(300);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"logAbandoned",type,false);                                                                                                          Value lhs3 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs2 = IntConstant.v(0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs2));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod1(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("getRemoveAbandoned",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$z0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"removeAbandoned",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$z0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod2(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("setRemoveAbandoned",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("z0", RefType.v("boolean")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"z0");                                                                                                        
                                                                                                        Type paramType0 = BooleanType.v();                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"removeAbandoned",type,false);                                                                                                          Value lhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs0 = localByName(b,"z0");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod3(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("getRemoveAbandonedTimeout",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i0", RefType.v("int")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$i0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"removeAbandonedTimeout",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$i0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod4(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("setRemoveAbandonedTimeout",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("i0", RefType.v("int")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"i0");                                                                                                        
                                                                                                        Type paramType0 = IntType.v();                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"removeAbandonedTimeout",type,false);                                                                                                          Value lhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs0 = localByName(b,"i0");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod5(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("getLogAbandoned",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$z0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"logAbandoned",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$z0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod6(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("setLogAbandoned",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("z0", RefType.v("boolean")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.AbandonedConfig");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"z0");                                                                                                        
                                                                                                        Type paramType0 = BooleanType.v();                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.AbandonedConfig"),"logAbandoned",type,false);                                                                                                          Value lhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs0 = localByName(b,"z0");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
