                                                                                                    import java.util.*;                                                                                                    
                                                                                                    import soot.*;                                                                                                    
                                                                                                    import soot.jimple.*;                                                                                                    
                                                                                                    import soot.util.*;                                                                                                    
                                                                                                                                                                                                        
                                                                                                    public class                                                                                                     org_apache_tomcat_dbcp_pool_impl_GenericKeyedObjectPool$ObjectQueue_Maker                                                                                                     {                                                                                                    
                                                                                                    private static Local localByName(Body b, String name) {                                                                                                    
                                                                                                    	for(Local l: b.getLocals()) {                                                                                                    
                                                                                                    		if(l.getName().equals(name))                                                                                                    
                                                                                                    			return l;                                                                                                    
                                                                                                    	}                                                                                                    
                                                                                                    	throw new IllegalArgumentException("No such local: "+name);                                                                                                    
                                                                                                    }                                                                                                    
                                                                                                      public void create() {                                                                                                      
                                                                                                        SootClass c = new SootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue");                                                                                                        
                                                                                                        c.setApplicationClass();                                                                                                        
                                                                                                        Scene.v().addClass(c);                                                                                                        
                                                                                                        createMethod0(c);                                                                                                        
                                                                                                        createMethod1(c);                                                                                                        
                                                                                                        createMethod2(c);                                                                                                        
                                                                                                        createMethod3(c);                                                                                                        
                                                                                                        createMethod4(c);                                                                                                        
                                                                                                        createMethod5(c);                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod0(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("org.apache.tomcat.dbcp.pool.impl.CursorableLinkedList")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"this$0",type,false);                                                                                                          Value lhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs0 = localByName(b,"r1");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Object"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"activeCount",type,false);                                                                                                          Value lhs3 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs1 = IntConstant.v(0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs1));                                                                                                        
                                                                                                        Local lhs4 = localByName(b,"$r2");                                                                                                        
                                                                                                        RefType type1 = RefType.v("org.apache.tomcat.dbcp.pool.impl.CursorableLinkedList");                                                                                                        
                                                                                                        Value rhs2 = Jimple.v().newNewExpr(type1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs2));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r2");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.CursorableLinkedList"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie1 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.pool.impl.CursorableLinkedList");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"queue",type,false);                                                                                                          Value lhs5 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs3 = localByName(b,"$r2");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs5,rhs3));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod1(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("incrementActiveCount",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i1", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i2", RefType.v("int")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"this$0",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = IntType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool"),"access$408",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$i1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"activeCount",type,false);                                                                                                          Value rhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"$i2");                                                                                                        
                                                                                                        Local left0 = localByName(b,"$i1");                                                                                                        
                                                                                                        Value right0 = IntConstant.v(1);                                                                                                        
                                                                                                        Value rhs2 = Jimple.v().newAddExpr(left0,right0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs2));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"activeCount",type,false);                                                                                                          Value lhs4 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs3 = localByName(b,"$i2");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs3));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod2(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("decrementActiveCount",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i1", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i2", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i3", RefType.v("int")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"this$0",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = IntType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool"),"access$410",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$i1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"activeCount",type,false);                                                                                                          Value rhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        Local left0 = localByName(b,"$i1");                                                                                                        
                                                                                                        Value right0 = IntConstant.v(0);                                                                                                        
                                                                                                        Value condition0 = Jimple.v().newLeExpr(left0,right0);                                                                                                        
                                                                                                        Unit target0=jumpTarget0;                                                                                                        
                                                                                                        units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"$i2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"activeCount",type,false);                                                                                                          Value rhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs2));                                                                                                        
                                                                                                        Local lhs4 = localByName(b,"$i3");                                                                                                        
                                                                                                        Local left1 = localByName(b,"$i2");                                                                                                        
                                                                                                        Value right1 = IntConstant.v(1);                                                                                                        
                                                                                                        Value rhs3 = Jimple.v().newSubExpr(left1,right1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs3));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"activeCount",type,false);                                                                                                          Value lhs5 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs4 = localByName(b,"$i3");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs5,rhs4));                                                                                                        
                                                                                                        units.add(jumpTarget0);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod3(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r2", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$1")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"r2");                                                                                                        
                                                                                                        RefType paramType1 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$1");                                                                                                        
                                                                                                        int number1=1;                                                                                                        
                                                                                                        Value idRef2 = Jimple.v().newParameterRef(paramType1, number1);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs2,idRef2));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod4(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("access$100",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("org.apache.tomcat.dbcp.pool.impl.CursorableLinkedList")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("org.apache.tomcat.dbcp.pool.impl.CursorableLinkedList");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"queue",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$r1");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod5(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("access$200",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i0", RefType.v("int")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$i0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = IntType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectQueue"),"activeCount",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$i0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
