                                                                                        import java.util.*;                                                                                        
                                                                                        import soot.*;                                                                                        
                                                                                        import soot.jimple.*;                                                                                        
                                                                                        import soot.util.*;                                                                                        
                                                                                                                                                                                
                                                                                        public class                                                                                         org_apache_tomcat_dbcp_pool_BaseKeyedObjectPool_Maker                                                                                         {                                                                                        
                                                                                        private static Local localByName(Body b, String name) {                                                                                        
                                                                                        	for(Local l: b.getLocals()) {                                                                                        
                                                                                        		if(l.getName().equals(name))                                                                                        
                                                                                        			return l;                                                                                        
                                                                                        	}                                                                                        
                                                                                        	throw new IllegalArgumentException("No such local: "+name);                                                                                        
                                                                                        }                                                                                        
                                                                                          public void create() {                                                                                          
                                                                                            SootClass c = new SootClass("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                            
                                                                                            c.setApplicationClass();                                                                                            
                                                                                            Scene.v().addClass(c);                                                                                            
                                                                                            createMethod0(c);                                                                                            
                                                                                            createMethod1(c);                                                                                            
                                                                                            createMethod2(c);                                                                                            
                                                                                            createMethod3(c);                                                                                            
                                                                                            createMethod4(c);                                                                                            
                                                                                            createMethod5(c);                                                                                            
                                                                                            createMethod6(c);                                                                                            
                                                                                            createMethod7(c);                                                                                            
                                                                                            createMethod8(c);                                                                                            
                                                                                            createMethod9(c);                                                                                            
                                                                                            createMethod10(c);                                                                                            
                                                                                            createMethod11(c);                                                                                            
                                                                                            createMethod12(c);                                                                                            
                                                                                            createMethod13(c);                                                                                            
                                                                                            createMethod14(c);                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                          public void createMethod0(SootClass c) {                                                                                          
                                                                                            SootMethod m = new SootMethod("<init>",null,null);                                                                                            
                                                                                            Body b = Jimple.v().newBody(m);                                                                                            
                                                                                            m.setActiveBody(b);                                                                                            
                                                                                            Chain<Local> locals = b.getLocals();                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                            
                                                                                            Chain<Unit> units = b.getUnits();                                                                                            
                                                                                            Local lhs0 = localByName(b,"r0");                                                                                            
                                                                                            RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                            
                                                                                            Value idRef0 = Jimple.v().newThisRef(type0);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"r0");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Object"),"<init>",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie0));                                                                                            
                                                                                            {                                                                                            
                                                                                              Type type = BooleanType.v();                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool"),"closed",type,false);                                                                                              Value lhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            Value rhs0 = IntConstant.v(0);                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                            
                                                                                            units.add(Jimple.v().newReturnVoidStmt());                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                          public void createMethod1(SootClass c) {                                                                                          
                                                                                            SootMethod m = new SootMethod("borrowObject",null,null);                                                                                            
                                                                                            Body b = Jimple.v().newBody(m);                                                                                            
                                                                                            m.setActiveBody(b);                                                                                            
                                                                                              public void createMethod1(SootClass c) {                                                                                              
                                                                                                SootMethod m = new SootMethod("returnObject",null,null);                                                                                                
                                                                                                Body b = Jimple.v().newBody(m);                                                                                                
                                                                                                m.setActiveBody(b);                                                                                                
                                                                                                  public void createMethod1(SootClass c) {                                                                                                  
                                                                                                    SootMethod m = new SootMethod("invalidateObject",null,null);                                                                                                    
                                                                                                    Body b = Jimple.v().newBody(m);                                                                                                    
                                                                                                    m.setActiveBody(b);                                                                                                    
                                                                                                      public void createMethod1(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("addObject",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("java.lang.UnsupportedOperationException")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r2");                                                                                                        
                                                                                                        RefType type1 = RefType.v("java.lang.UnsupportedOperationException");                                                                                                        
                                                                                                        Value rhs0 = Jimple.v().newNewExpr(type1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r2");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.UnsupportedOperationException"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local op0 = localByName(b,"$r2");                                                                                                        
                                                                                                        units.add(Jimple.v().newThrowStmt(op0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod2(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("getNumIdle",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Value retVal0 = IntConstant.v(-1);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod3(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("getNumActive",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Value retVal0 = IntConstant.v(-1);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod4(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("getNumIdle",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Value retVal0 = IntConstant.v(-1);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod5(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("getNumActive",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Value retVal0 = IntConstant.v(-1);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod6(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("clear",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("java.lang.UnsupportedOperationException")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        RefType type1 = RefType.v("java.lang.UnsupportedOperationException");                                                                                                        
                                                                                                        Value rhs0 = Jimple.v().newNewExpr(type1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.UnsupportedOperationException"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local op0 = localByName(b,"$r1");                                                                                                        
                                                                                                        units.add(Jimple.v().newThrowStmt(op0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod7(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("clear",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("java.lang.UnsupportedOperationException")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r2");                                                                                                        
                                                                                                        RefType type1 = RefType.v("java.lang.UnsupportedOperationException");                                                                                                        
                                                                                                        Value rhs0 = Jimple.v().newNewExpr(type1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r2");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.UnsupportedOperationException"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local op0 = localByName(b,"$r2");                                                                                                        
                                                                                                        units.add(Jimple.v().newThrowStmt(op0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod8(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("close",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool"),"closed",type,false);                                                                                                          Value lhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Value rhs0 = IntConstant.v(1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod9(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("setFactory",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("org.apache.tomcat.dbcp.pool.KeyedPoolableObjectFactory")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("java.lang.UnsupportedOperationException")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.pool.KeyedPoolableObjectFactory");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r2");                                                                                                        
                                                                                                        RefType type1 = RefType.v("java.lang.UnsupportedOperationException");                                                                                                        
                                                                                                        Value rhs0 = Jimple.v().newNewExpr(type1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r2");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.UnsupportedOperationException"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local op0 = localByName(b,"$r2");                                                                                                        
                                                                                                        units.add(Jimple.v().newThrowStmt(op0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod10(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("isClosed",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$z0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = BooleanType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool"),"closed",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$z0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod11(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("assertOpen",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("java.lang.IllegalStateException")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$z0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = BooleanType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.BaseKeyedObjectPool"),"isClosed",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs0 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        Local left0 = localByName(b,"$z0");                                                                                                        
                                                                                                        Value right0 = IntConstant.v(0);                                                                                                        
                                                                                                        Value condition0 = Jimple.v().newEqExpr(left0,right0);                                                                                                        
                                                                                                        Unit target0=jumpTarget0;                                                                                                        
                                                                                                        units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r1");                                                                                                        
                                                                                                        RefType type1 = RefType.v("java.lang.IllegalStateException");                                                                                                        
                                                                                                        Value rhs1 = Jimple.v().newNewExpr(type1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("java.lang.String");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.IllegalStateException"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local op0 = localByName(b,"$r1");                                                                                                        
                                                                                                        units.add(Jimple.v().newThrowStmt(op0));                                                                                                        
                                                                                                        units.add(jumpTarget0);                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
