                                                                                        import java.util.*;                                                                                        
                                                                                        import soot.*;                                                                                        
                                                                                        import soot.jimple.*;                                                                                        
                                                                                        import soot.util.*;                                                                                        
                                                                                                                                                                                
                                                                                        public class                                                                                         org_apache_tomcat_dbcp_dbcp_SQLNestedException_Maker                                                                                         {                                                                                        
                                                                                        private static Local localByName(Body b, String name) {                                                                                        
                                                                                        	for(Local l: b.getLocals()) {                                                                                        
                                                                                        		if(l.getName().equals(name))                                                                                        
                                                                                        			return l;                                                                                        
                                                                                        	}                                                                                        
                                                                                        	throw new IllegalArgumentException("No such local: "+name);                                                                                        
                                                                                        }                                                                                        
                                                                                          public void create() {                                                                                          
                                                                                            SootClass c = new SootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException");                                                                                            
                                                                                            c.setApplicationClass();                                                                                            
                                                                                            Scene.v().addClass(c);                                                                                            
                                                                                            createMethod0(c);                                                                                            
                                                                                            createMethod1(c);                                                                                            
                                                                                            createMethod2(c);                                                                                            
                                                                                            createMethod3(c);                                                                                            
                                                                                            createMethod4(c);                                                                                            
                                                                                            createMethod5(c);                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                          public void createMethod0(SootClass c) {                                                                                          
                                                                                            SootMethod m = new SootMethod("hasThrowableCauseMethod",null,null);                                                                                            
                                                                                            Body b = Jimple.v().newBody(m);                                                                                            
                                                                                            m.setActiveBody(b);                                                                                            
                                                                                            Chain<Local> locals = b.getLocals();                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r0", RefType.v("java.lang.reflect.Method")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                            
                                                                                            Chain<Unit> units = b.getUnits();                                                                                            
                                                                                            NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                            
                                                                                            NopStmt jumpTarget1= Jimple.v().newNopStmt();                                                                                            
                                                                                            Local lhs0 = localByName(b,"$r0");                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.reflect.Method");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"THROWABLE_CAUSE_METHOD",type,true);                                                                                              Value rhs0 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs0,rhs0));                                                                                            
                                                                                            Local left0 = localByName(b,"$r0");                                                                                            
                                                                                            Value right0 = NullConstant.v();                                                                                            
                                                                                            Value condition0 = Jimple.v().newEqExpr(left0,right0);                                                                                            
                                                                                            Unit target0=jumpTarget0;                                                                                            
                                                                                            units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                            
                                                                                            Local lhs1 = localByName(b,"$z0");                                                                                            
                                                                                            Value rhs1 = IntConstant.v(1);                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs1,rhs1));                                                                                            
                                                                                            Unit target1=jumpTarget1;                                                                                            
                                                                                            units.add(Jimple.v().newGotoStmt(target1));                                                                                            
                                                                                            Local lhs2 = localByName(b,"$z0");                                                                                            
                                                                                            Value rhs2 = IntConstant.v(0);                                                                                            
                                                                                            units.add(jumpTarget0);                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs2,rhs2));                                                                                            
                                                                                            Local retVal0 = localByName(b,"$z0");                                                                                            
                                                                                            units.add(jumpTarget1);                                                                                            
                                                                                            units.add(Jimple.v().newReturnStmt(retVal0));                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                          public void createMethod1(SootClass c) {                                                                                          
                                                                                            SootMethod m = new SootMethod("<init>",null,null);                                                                                            
                                                                                            Body b = Jimple.v().newBody(m);                                                                                            
                                                                                            m.setActiveBody(b);                                                                                            
                                                                                            Chain<Local> locals = b.getLocals();                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.SQLNestedException")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.String")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r2", RefType.v("java.lang.Throwable")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r3", RefType.v("java.io.PrintWriter")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r4", RefType.v("java.io.PrintWriter")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r5", RefType.v("java.io.PrintWriter")));                                                                                            
                                                                                            Chain<Unit> units = b.getUnits();                                                                                            
                                                                                            NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                            
                                                                                            NopStmt jumpTarget1= Jimple.v().newNopStmt();                                                                                            
                                                                                            Local lhs0 = localByName(b,"r0");                                                                                            
                                                                                            RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.SQLNestedException");                                                                                            
                                                                                            Value idRef0 = Jimple.v().newThisRef(type0);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                            
                                                                                            Local lhs1 = localByName(b,"r1");                                                                                            
                                                                                            RefType paramType0 = RefType.v("java.lang.String");                                                                                            
                                                                                            int number0=0;                                                                                            
                                                                                            Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                            
                                                                                            Local lhs2 = localByName(b,"r2");                                                                                            
                                                                                            RefType paramType1 = RefType.v("java.lang.Throwable");                                                                                            
                                                                                            int number1=1;                                                                                            
                                                                                            Value idRef2 = Jimple.v().newParameterRef(paramType1, number1);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs2,idRef2));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"r0");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.lang.String");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.sql.SQLException"),"<init>",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie0));                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.Throwable");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"cause",type,false);                                                                                              Value lhs3 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            Value rhs0 = NullConstant.v();                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs3,rhs0));                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.Throwable");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"cause",type,false);                                                                                              Value lhs4 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            Local rhs1 = localByName(b,"r2");                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs4,rhs1));                                                                                            
                                                                                            Local left0 = localByName(b,"r2");                                                                                            
                                                                                            Value right0 = NullConstant.v();                                                                                            
                                                                                            Value condition0 = Jimple.v().newEqExpr(left0,right0);                                                                                            
                                                                                            Unit target0=jumpTarget0;                                                                                            
                                                                                            units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                            
                                                                                            Local lhs5 = localByName(b,"$r3");                                                                                            
                                                                                            {                                                                                            
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType returnType = RefType.v("java.io.PrintWriter");                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.sql.DriverManager"),"getLogWriter",parameterTypes,returnType,true);                                                                                              
                                                                                              Value rhs2 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs5,rhs2));                                                                                            
                                                                                            Local left1 = localByName(b,"$r3");                                                                                            
                                                                                            Value right1 = NullConstant.v();                                                                                            
                                                                                            Value condition1 = Jimple.v().newEqExpr(left1,right1);                                                                                            
                                                                                            Unit target1=jumpTarget0;                                                                                            
                                                                                            units.add(Jimple.v().newIfStmt(condition1,target1));                                                                                            
                                                                                            Local lhs6 = localByName(b,"$r4");                                                                                            
                                                                                            {                                                                                            
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType returnType = RefType.v("java.io.PrintWriter");                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.sql.DriverManager"),"getLogWriter",parameterTypes,returnType,true);                                                                                              
                                                                                              Value rhs3 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs6,rhs3));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"$r4");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.lang.String");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.io.PrintWriter"),"print",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie1));                                                                                            
                                                                                            Local lhs7 = localByName(b,"$r5");                                                                                            
                                                                                            {                                                                                            
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType returnType = RefType.v("java.io.PrintWriter");                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.sql.DriverManager"),"getLogWriter",parameterTypes,returnType,true);                                                                                              
                                                                                              Value rhs4 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs7,rhs4));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"r2");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.io.PrintWriter");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Throwable"),"printStackTrace",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie2 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie2));                                                                                            
                                                                                            units.add(jumpTarget0);                                                                                            
                                                                                            units.add(Jimple.v().newReturnVoidStmt());                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                          public void createMethod2(SootClass c) {                                                                                          
                                                                                            SootMethod m = new SootMethod("getCause",null,null);                                                                                            
                                                                                            Body b = Jimple.v().newBody(m);                                                                                            
                                                                                            m.setActiveBody(b);                                                                                            
                                                                                            Chain<Local> locals = b.getLocals();                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.SQLNestedException")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r1", RefType.v("java.lang.Throwable")));                                                                                            
                                                                                            Chain<Unit> units = b.getUnits();                                                                                            
                                                                                            Local lhs0 = localByName(b,"r0");                                                                                            
                                                                                            RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.SQLNestedException");                                                                                            
                                                                                            Value idRef0 = Jimple.v().newThisRef(type0);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                            
                                                                                            Local lhs1 = localByName(b,"$r1");                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.Throwable");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"cause",type,false);                                                                                              Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                            
                                                                                            Local retVal0 = localByName(b,"$r1");                                                                                            
                                                                                            units.add(Jimple.v().newReturnStmt(retVal0));                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                          public void createMethod3(SootClass c) {                                                                                          
                                                                                            SootMethod m = new SootMethod("printStackTrace",null,null);                                                                                            
                                                                                            Body b = Jimple.v().newBody(m);                                                                                            
                                                                                            m.setActiveBody(b);                                                                                            
                                                                                            Chain<Local> locals = b.getLocals();                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.SQLNestedException")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r1", RefType.v("java.io.PrintStream")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r2", RefType.v("java.lang.Throwable")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r3", RefType.v("java.lang.Throwable")));                                                                                            
                                                                                            Chain<Unit> units = b.getUnits();                                                                                            
                                                                                            NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                            
                                                                                            NopStmt jumpTarget1= Jimple.v().newNopStmt();                                                                                            
                                                                                            Local lhs0 = localByName(b,"r0");                                                                                            
                                                                                            RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.SQLNestedException");                                                                                            
                                                                                            Value idRef0 = Jimple.v().newThisRef(type0);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                            
                                                                                            Local lhs1 = localByName(b,"r1");                                                                                            
                                                                                            RefType paramType0 = RefType.v("java.io.PrintStream");                                                                                            
                                                                                            int number0=0;                                                                                            
                                                                                            Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"r0");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.io.PrintStream");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Throwable"),"printStackTrace",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie0));                                                                                            
                                                                                            Local lhs2 = localByName(b,"$r2");                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.Throwable");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"cause",type,false);                                                                                              Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                            
                                                                                            Local left0 = localByName(b,"$r2");                                                                                            
                                                                                            Value right0 = NullConstant.v();                                                                                            
                                                                                            Value condition0 = Jimple.v().newEqExpr(left0,right0);                                                                                            
                                                                                            Unit target0=jumpTarget0;                                                                                            
                                                                                            units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                            
                                                                                            Local lhs3 = localByName(b,"$z0");                                                                                            
                                                                                            {                                                                                            
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              Type returnType = BooleanType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"hasThrowableCauseMethod",parameterTypes,returnType,true);                                                                                              
                                                                                              Value rhs1 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs3,rhs1));                                                                                            
                                                                                            Local left1 = localByName(b,"$z0");                                                                                            
                                                                                            Value right1 = IntConstant.v(0);                                                                                            
                                                                                            Value condition1 = Jimple.v().newNeExpr(left1,right1);                                                                                            
                                                                                            Unit target1=jumpTarget0;                                                                                            
                                                                                            units.add(Jimple.v().newIfStmt(condition1,target1));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"r1");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.lang.String");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.io.PrintStream"),"print",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie1));                                                                                            
                                                                                            Local lhs4 = localByName(b,"$r3");                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.Throwable");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"cause",type,false);                                                                                              Value rhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs4,rhs2));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"$r3");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.io.PrintStream");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Throwable"),"printStackTrace",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie2 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie2));                                                                                            
                                                                                            units.add(jumpTarget0);                                                                                            
                                                                                            units.add(Jimple.v().newReturnVoidStmt());                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                          public void createMethod4(SootClass c) {                                                                                          
                                                                                            SootMethod m = new SootMethod("printStackTrace",null,null);                                                                                            
                                                                                            Body b = Jimple.v().newBody(m);                                                                                            
                                                                                            m.setActiveBody(b);                                                                                            
                                                                                            Chain<Local> locals = b.getLocals();                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.dbcp.SQLNestedException")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r1", RefType.v("java.io.PrintWriter")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r2", RefType.v("java.lang.Throwable")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$z0", RefType.v("boolean")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r3", RefType.v("java.lang.Throwable")));                                                                                            
                                                                                            Chain<Unit> units = b.getUnits();                                                                                            
                                                                                            NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                            
                                                                                            NopStmt jumpTarget1= Jimple.v().newNopStmt();                                                                                            
                                                                                            Local lhs0 = localByName(b,"r0");                                                                                            
                                                                                            RefType type0 = RefType.v("org.apache.tomcat.dbcp.dbcp.SQLNestedException");                                                                                            
                                                                                            Value idRef0 = Jimple.v().newThisRef(type0);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                            
                                                                                            Local lhs1 = localByName(b,"r1");                                                                                            
                                                                                            RefType paramType0 = RefType.v("java.io.PrintWriter");                                                                                            
                                                                                            int number0=0;                                                                                            
                                                                                            Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"r0");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.io.PrintWriter");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Throwable"),"printStackTrace",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie0));                                                                                            
                                                                                            Local lhs2 = localByName(b,"$r2");                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.Throwable");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"cause",type,false);                                                                                              Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                            
                                                                                            Local left0 = localByName(b,"$r2");                                                                                            
                                                                                            Value right0 = NullConstant.v();                                                                                            
                                                                                            Value condition0 = Jimple.v().newEqExpr(left0,right0);                                                                                            
                                                                                            Unit target0=jumpTarget0;                                                                                            
                                                                                            units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                            
                                                                                            Local lhs3 = localByName(b,"$z0");                                                                                            
                                                                                            {                                                                                            
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              Type returnType = BooleanType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"hasThrowableCauseMethod",parameterTypes,returnType,true);                                                                                              
                                                                                              Value rhs1 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs3,rhs1));                                                                                            
                                                                                            Local left1 = localByName(b,"$z0");                                                                                            
                                                                                            Value right1 = IntConstant.v(0);                                                                                            
                                                                                            Value condition1 = Jimple.v().newNeExpr(left1,right1);                                                                                            
                                                                                            Unit target1=jumpTarget0;                                                                                            
                                                                                            units.add(Jimple.v().newIfStmt(condition1,target1));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"r1");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.lang.String");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.io.PrintWriter"),"print",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie1));                                                                                            
                                                                                            Local lhs4 = localByName(b,"$r3");                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.Throwable");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"cause",type,false);                                                                                              Value rhs2 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs4,rhs2));                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"$r3");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.io.PrintWriter");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              Type returnType = VoidType.v();                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Throwable"),"printStackTrace",parameterTypes,returnType,false);                                                                                              
                                                                                              Value ie2 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newInvokeStmt(ie2));                                                                                            
                                                                                            units.add(jumpTarget0);                                                                                            
                                                                                            units.add(Jimple.v().newReturnVoidStmt());                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                          public void createMethod5(SootClass c) {                                                                                          
                                                                                            SootMethod m = new SootMethod("<clinit>",null,null);                                                                                            
                                                                                            Body b = Jimple.v().newBody(m);                                                                                            
                                                                                            m.setActiveBody(b);                                                                                            
                                                                                            Chain<Local> locals = b.getLocals();                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r0", RefType.v("java.lang.Class")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.reflect.Method")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("r2", RefType.v("java.lang.Exception")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r3", RefType.v("java.lang.Class[]")));                                                                                            
                                                                                            locals.add(Jimple.v().newLocal("$r4", RefType.v("java.lang.Exception")));                                                                                            
                                                                                            Chain<Unit> units = b.getUnits();                                                                                            
                                                                                            NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                            
                                                                                            Local lhs0 = localByName(b,"$r0");                                                                                            
                                                                                            Value rhs0 = ClassConstant.v("java/lang/Throwable");                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs0,rhs0));                                                                                            
                                                                                            Local lhs1 = localByName(b,"$r3");                                                                                            
                                                                                            RefType baseType = RefType.v("java.lang.Class");                                                                                            
                                                                                            int numDimensions=1;                                                                                            
                                                                                            Type type0 = ArrayType.v(baseType, numDimensions);                                                                                            
                                                                                            Value op0 = NullConstant.v();                                                                                            
                                                                                            Value rhs1 = Jimple.v().newCastExpr(type0,op0);                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs1,rhs1));                                                                                            
                                                                                            Local lhs2 = localByName(b,"r1");                                                                                            
                                                                                            {                                                                                            
                                                                                              Local base = localByName(b,"$r0");                                                                                              
                                                                                              List<Type> parameterTypes = new LinkedList<Type>();                                                                                              
                                                                                              RefType type0 = RefType.v("java.lang.String");                                                                                              
                                                                                              parameterTypes.add(type0);                                                                                              
                                                                                              RefType baseType = RefType.v("java.lang.Class");                                                                                              
                                                                                              int numDimensions=1;                                                                                              
                                                                                              Type type1 = ArrayType.v(baseType, numDimensions);                                                                                              
                                                                                              parameterTypes.add(type1);                                                                                              
                                                                                              RefType returnType = RefType.v("java.lang.reflect.Method");                                                                                              
                                                                                              SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Class"),"getMethod",parameterTypes,returnType,false);                                                                                              
                                                                                              Value rhs2 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs2,rhs2));                                                                                            
                                                                                            Unit target0=jumpTarget0;                                                                                            
                                                                                            units.add(Jimple.v().newGotoStmt(target0));                                                                                            
                                                                                            Local lhs3 = localByName(b,"$r4");                                                                                            
                                                                                            Value idRef0 = Jimple.v().newCaughtExceptionRef();                                                                                            
                                                                                            units.add(Jimple.v().newIdentityStmt(lhs3,idRef0));                                                                                            
                                                                                            Local lhs4 = localByName(b,"r2");                                                                                            
                                                                                            Local rhs3 = localByName(b,"$r4");                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs4,rhs3));                                                                                            
                                                                                            Local lhs5 = localByName(b,"r1");                                                                                            
                                                                                            Value rhs4 = NullConstant.v();                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs5,rhs4));                                                                                            
                                                                                            {                                                                                            
                                                                                              RefType type = RefType.v("java.lang.reflect.Method");                                                                                              
                                                                                              SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.dbcp.SQLNestedException"),"THROWABLE_CAUSE_METHOD",type,true);                                                                                              Value lhs6 = Jimple.v().newStaticFieldRef(fieldRef);                                                                                              
                                                                                            }                                                                                            
                                                                                            Local rhs5 = localByName(b,"r1");                                                                                            
                                                                                            units.add(jumpTarget0);                                                                                            
                                                                                            units.add(Jimple.v().newAssignStmt(lhs6,rhs5));                                                                                            
                                                                                            units.add(Jimple.v().newReturnVoidStmt());                                                                                            
                                                                                          }                                                                                          
                                                                                                                                                                                
                                                                                        }                                                                                        
