                                                                                                    import java.util.*;                                                                                                    
                                                                                                    import soot.*;                                                                                                    
                                                                                                    import soot.jimple.*;                                                                                                    
                                                                                                    import soot.util.*;                                                                                                    
                                                                                                                                                                                                        
                                                                                                    public class                                                                                                     org_apache_tomcat_dbcp_pool_impl_GenericKeyedObjectPool$ObjectTimestampPair_Maker                                                                                                     {                                                                                                    
                                                                                                    private static Local localByName(Body b, String name) {                                                                                                    
                                                                                                    	for(Local l: b.getLocals()) {                                                                                                    
                                                                                                    		if(l.getName().equals(name))                                                                                                    
                                                                                                    			return l;                                                                                                    
                                                                                                    	}                                                                                                    
                                                                                                    	throw new IllegalArgumentException("No such local: "+name);                                                                                                    
                                                                                                    }                                                                                                    
                                                                                                      public void create() {                                                                                                      
                                                                                                        SootClass c = new SootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                        
                                                                                                        c.setApplicationClass();                                                                                                        
                                                                                                        Scene.v().addClass(c);                                                                                                        
                                                                                                        createMethod0(c);                                                                                                        
                                                                                                        createMethod1(c);                                                                                                        
                                                                                                        createMethod2(c);                                                                                                        
                                                                                                        createMethod3(c);                                                                                                        
                                                                                                        createMethod4(c);                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod0(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$l0", RefType.v("long")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$l0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = LongType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.System"),"currentTimeMillis",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value rhs0 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("java.lang.Object");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type type1 = LongType.v();                                                                                                          
                                                                                                          parameterTypes.add(type1);                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod1(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("<init>",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("l0", RefType.v("long")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"l0");                                                                                                        
                                                                                                        Type paramType1 = LongType.v();                                                                                                        
                                                                                                        int number1=1;                                                                                                        
                                                                                                        Value idRef2 = Jimple.v().newParameterRef(paramType1, number1);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs2,idRef2));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Object"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("java.lang.Object");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair"),"value",type,false);                                                                                                          Value lhs3 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs0 = localByName(b,"r1");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = LongType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair"),"tstamp",type,false);                                                                                                          Value lhs4 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        Local rhs1 = localByName(b,"l0");                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs1));                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnVoidStmt());                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod2(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("toString",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r1", RefType.v("java.lang.StringBuilder")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r3", RefType.v("java.lang.StringBuilder")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r4", RefType.v("java.lang.StringBuilder")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$l0", RefType.v("long")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r5", RefType.v("java.lang.StringBuilder")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r6", RefType.v("java.lang.String")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"$r1");                                                                                                        
                                                                                                        RefType type1 = RefType.v("java.lang.StringBuilder");                                                                                                        
                                                                                                        Value rhs0 = Jimple.v().newNewExpr(type1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs1,rhs0));                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type returnType = VoidType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.StringBuilder"),"<init>",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value ie0 = Jimple.v().newSpecialInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newInvokeStmt(ie0));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          RefType type = RefType.v("java.lang.Object");                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair"),"value",type,false);                                                                                                          Value rhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs1));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"$r3");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r1");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("java.lang.Object");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          RefType returnType = RefType.v("java.lang.StringBuilder");                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.StringBuilder"),"append",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs2 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs2));                                                                                                        
                                                                                                        Local lhs4 = localByName(b,"$r4");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r3");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("java.lang.String");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          RefType returnType = RefType.v("java.lang.StringBuilder");                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.StringBuilder"),"append",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs3 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs3));                                                                                                        
                                                                                                        Local lhs5 = localByName(b,"$l0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = LongType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair"),"tstamp",type,false);                                                                                                          Value rhs4 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs5,rhs4));                                                                                                        
                                                                                                        Local lhs6 = localByName(b,"$r5");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r4");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type type0 = LongType.v();                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          RefType returnType = RefType.v("java.lang.StringBuilder");                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.StringBuilder"),"append",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs5 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs6,rhs5));                                                                                                        
                                                                                                        Local lhs7 = localByName(b,"$r6");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"$r5");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType returnType = RefType.v("java.lang.String");                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.StringBuilder"),"toString",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs6 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs7,rhs6));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$r6");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod3(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("compareTo",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("java.lang.Object")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$r2", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i0", RefType.v("int")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("java.lang.Object");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$r2");                                                                                                        
                                                                                                        RefType type1 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                        
                                                                                                        Local op0 = localByName(b,"r1");                                                                                                        
                                                                                                        Value rhs0 = Jimple.v().newCastExpr(type1,op0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"$i0");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Local base = localByName(b,"r0");                                                                                                          
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = IntType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair"),"compareTo",parameterTypes,returnType,false);                                                                                                          
                                                                                                          Value rhs1 = Jimple.v().newVirtualInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs1));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$i0");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                      public void createMethod4(SootClass c) {                                                                                                      
                                                                                                        SootMethod m = new SootMethod("compareTo",null,null);                                                                                                        
                                                                                                        Body b = Jimple.v().newBody(m);                                                                                                        
                                                                                                        m.setActiveBody(b);                                                                                                        
                                                                                                        Chain<Local> locals = b.getLocals();                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r0", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("r1", RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("l0", RefType.v("long")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$l1", RefType.v("long")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$l2", RefType.v("long")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$b3", RefType.v("byte")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i4", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i5", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i6", RefType.v("int")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$l7", RefType.v("long")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$l8", RefType.v("long")));                                                                                                        
                                                                                                        locals.add(Jimple.v().newLocal("$i9", RefType.v("int")));                                                                                                        
                                                                                                        Chain<Unit> units = b.getUnits();                                                                                                        
                                                                                                        NopStmt jumpTarget0= Jimple.v().newNopStmt();                                                                                                        
                                                                                                        Local lhs0 = localByName(b,"r0");                                                                                                        
                                                                                                        RefType type0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                        
                                                                                                        Value idRef0 = Jimple.v().newThisRef(type0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs0,idRef0));                                                                                                        
                                                                                                        Local lhs1 = localByName(b,"r1");                                                                                                        
                                                                                                        RefType paramType0 = RefType.v("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair");                                                                                                        
                                                                                                        int number0=0;                                                                                                        
                                                                                                        Value idRef1 = Jimple.v().newParameterRef(paramType0, number0);                                                                                                        
                                                                                                        units.add(Jimple.v().newIdentityStmt(lhs1,idRef1));                                                                                                        
                                                                                                        Local lhs2 = localByName(b,"$l1");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = LongType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair"),"tstamp",type,false);                                                                                                          Value rhs0 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs2,rhs0));                                                                                                        
                                                                                                        Local lhs3 = localByName(b,"$l2");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          Type type = LongType.v();                                                                                                          
                                                                                                          SootFieldRef fieldRef = Scene.v().makeFieldRef(Scene.v().getSootClass("org.apache.tomcat.dbcp.pool.impl.GenericKeyedObjectPool$ObjectTimestampPair"),"tstamp",type,false);                                                                                                          Value rhs1 = Jimple.v().newJInstanceFieldRef(fieldRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs3,rhs1));                                                                                                        
                                                                                                        Local lhs4 = localByName(b,"l0");                                                                                                        
                                                                                                        Local left0 = localByName(b,"$l1");                                                                                                        
                                                                                                        Local right0 = localByName(b,"$l2");                                                                                                        
                                                                                                        Value rhs2 = Jimple.v().newSubExpr(left0,right0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs4,rhs2));                                                                                                        
                                                                                                        Local lhs5 = localByName(b,"$b3");                                                                                                        
                                                                                                        Local left1 = localByName(b,"l0");                                                                                                        
                                                                                                        Value right1 = LongConstant.v(0);                                                                                                        
                                                                                                        Value rhs3 = Jimple.v().newCmpExpr(left1,right1);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs5,rhs3));                                                                                                        
                                                                                                        Local left2 = localByName(b,"$b3");                                                                                                        
                                                                                                        Value right2 = IntConstant.v(0);                                                                                                        
                                                                                                        Value condition0 = Jimple.v().newNeExpr(left2,right2);                                                                                                        
                                                                                                        Unit target0=jumpTarget0;                                                                                                        
                                                                                                        units.add(Jimple.v().newIfStmt(condition0,target0));                                                                                                        
                                                                                                        Local lhs6 = localByName(b,"$i4");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("java.lang.Object");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = IntType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.System"),"identityHashCode",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value rhs4 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs6,rhs4));                                                                                                        
                                                                                                        Local lhs7 = localByName(b,"$i5");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          RefType type0 = RefType.v("java.lang.Object");                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type returnType = IntType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.System"),"identityHashCode",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value rhs5 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs7,rhs5));                                                                                                        
                                                                                                        Local lhs8 = localByName(b,"$i6");                                                                                                        
                                                                                                        Local left3 = localByName(b,"$i4");                                                                                                        
                                                                                                        Local right3 = localByName(b,"$i5");                                                                                                        
                                                                                                        Value rhs6 = Jimple.v().newSubExpr(left3,right3);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs8,rhs6));                                                                                                        
                                                                                                        Local retVal0 = localByName(b,"$i6");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal0));                                                                                                        
                                                                                                        Local lhs9 = localByName(b,"$l7");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type type0 = LongType.v();                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type type1 = LongType.v();                                                                                                          
                                                                                                          parameterTypes.add(type1);                                                                                                          
                                                                                                          Type returnType = LongType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Math"),"max",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value rhs7 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(jumpTarget0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs9,rhs7));                                                                                                        
                                                                                                        Local lhs10 = localByName(b,"$l8");                                                                                                        
                                                                                                        {                                                                                                        
                                                                                                          List<Type> parameterTypes = new LinkedList<Type>();                                                                                                          
                                                                                                          Type type0 = LongType.v();                                                                                                          
                                                                                                          parameterTypes.add(type0);                                                                                                          
                                                                                                          Type type1 = LongType.v();                                                                                                          
                                                                                                          parameterTypes.add(type1);                                                                                                          
                                                                                                          Type returnType = LongType.v();                                                                                                          
                                                                                                          SootMethodRef methodRef = Scene.v().makeMethodRef(Scene.v().getSootClass("java.lang.Math"),"min",parameterTypes,returnType,true);                                                                                                          
                                                                                                          Value rhs8 = Jimple.v().newStaticInvokeExpr(base,methodRef);                                                                                                          
                                                                                                        }                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs10,rhs8));                                                                                                        
                                                                                                        Local lhs11 = localByName(b,"$i9");                                                                                                        
                                                                                                        Type type1 = IntType.v();                                                                                                        
                                                                                                        Local op0 = localByName(b,"$l8");                                                                                                        
                                                                                                        Value rhs9 = Jimple.v().newCastExpr(type1,op0);                                                                                                        
                                                                                                        units.add(Jimple.v().newAssignStmt(lhs11,rhs9));                                                                                                        
                                                                                                        Local retVal1 = localByName(b,"$i9");                                                                                                        
                                                                                                        units.add(Jimple.v().newReturnStmt(retVal1));                                                                                                        
                                                                                                      }                                                                                                      
                                                                                                                                                                                                        
                                                                                                    }                                                                                                    
